#!/usr/bin/env python3
"""Generate Android picker constants from the locked neutral token source."""

from __future__ import annotations

import hashlib
import json
import pathlib
import re
import sys


def constant(name: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).upper()


def argb(value: str) -> str:
    raw = value.removeprefix("#")
    if len(raw) == 6:
        raw = "FF" + raw
    return "0x" + raw.upper()


def joined(prefix: str, name: str) -> str:
    return prefix + name[:1].upper() + name[1:]


def main() -> int:
    if len(sys.argv) != 2:
        print("usage: generate-picker-tokens.py <picker_tokens.json>", file=sys.stderr)
        return 2
    source = pathlib.Path(sys.argv[1]).read_bytes()
    payload = json.loads(source)
    digest = hashlib.sha256(source).hexdigest()
    print("// Generated by scripts/generate-picker-tokens.py. Do not edit by hand.")
    print("package io.seatlayer.android.compose")
    print()
    print("internal object SeatLayerPickerTokens {")
    print(f'    const val SOURCE_SHA256: String = "{digest}"')
    for mode, roles in payload["color"].items():
        for name, value in roles.items():
            print(f"    const val {constant(joined(mode, name))}: Long = {argb(value)}")
    for section in ("size", "radius", "elevation"):
        for name, value in payload[section].items():
            suffix = "F" if isinstance(value, float) else ""
            print(f"    const val {constant(joined(section, name))} = {value}{suffix}")
    for name, value in payload["motion"]["duration"].items():
        print(f"    const val {constant(joined('motion', name))}_MILLIS = {value}")
    undo = payload["motion"]["durationOutsideBudget"]["undoWindow"]
    print(f"    const val MOTION_UNDO_WINDOW_MILLIS = {undo}")
    print("}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
