#!/usr/bin/env python3
"""Generate the checked-in Kotlin picker locale catalogue from locked JSON."""

from __future__ import annotations

import hashlib
import json
import pathlib
import sys


def kotlin_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False).replace("$", r"\$")


def main() -> int:
    if len(sys.argv) not in (2, 3):
        print(
            "usage: generate-picker-locales.py <locale_strings.json> [output.kt]",
            file=sys.stderr,
        )
        return 2
    source = pathlib.Path(sys.argv[1]).read_bytes()
    payload = json.loads(source)
    dictionaries = payload["strings"]
    digest = hashlib.sha256(source).hexdigest()
    lines = [
        "// Generated by scripts/generate-picker-locales.py. Do not edit by hand.",
        "package io.seatlayer.android.compose",
        "",
        "internal object SeatLayerPickerLocaleData {",
        f'    const val SOURCE_SHA256: String = "{digest}"',
        "    val dictionaries: Map<String, Map<String, String>> = mapOf(",
    ]
    for language in sorted(dictionaries):
        lines.append(f"        {kotlin_string(language)} to mapOf(")
        entries = sorted(dictionaries[language].items())
        for index in range(0, len(entries), 2):
            pair = entries[index : index + 2]
            rendered = " ".join(
                f"{kotlin_string(key)} to {kotlin_string(value)},"
                for key, value in pair
            )
            lines.append(f"            {rendered}")
        lines.append("        ),")
    lines.extend(("    )", "}"))
    output = "\n".join(lines) + "\n"
    if len(sys.argv) == 3:
        pathlib.Path(sys.argv[2]).write_text(output, encoding="utf-8")
    else:
        print(output, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
